version: '2'
services:
    betchampion-app:
        image: betchampion
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://betchampion-mysql:3306/betchampion?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    betchampion-mysql:
        extends:
            file: mysql.yml
            service: betchampion-mysql
